Retrieve all columns from the "categories" table.
Select distinct values from the "brand_name" column in the "brands" table.
Calculate the average list price of products.
Count the number of customers in the "customers" table.
Filter orders with an order status of "Pending" from the "orders" table.
Retrieve the first and last names of customers.
Calculate the total quantity of items in the "order_items" table.
Find the maximum list price among products.
Sort the products by model year in ascending order.
Get the total number of stores in each city.
Retrieve the customer details with the highest order quantity.
Calculate the average discount applied to orders.
Get the names of staff members who are currently active.
Count the number of products in each category.
Filter customers by zip code, excluding a specific value.
--
Retrieve the order details for a specific customer.
Calculate the total revenue generated by each store.
Find the minimum list price among products.
Sort the customers by last name in descending order.
Get the number of orders placed on a specific date.
Retrieve the products with a list price greater than $500.
Count the number of staff members in each store.
Filter orders by the shipped date, including a specific range.
Retrieve the average quantity of items per order.
Calculate the total discount amount for each order.
Get the staff details who have a manager assigned.
Find the highest quantity of a product in stock.
Sort the orders by order date in descending order.
Retrieve the customers who have not placed any orders.
Calculate the total revenue generated by each category.
Count the number of products in stock for each store.
Filter staff members by their email addresses.
Retrieve the orders placed by a specific staff member.
Calculate the average discount percentage for orders.
Get the store details with the highest revenue.
Find the products with a model year between two specific years.
Sort the staff members by their first names in ascending order.
Retrieve the orders that have been rejected.
Calculate the total revenue generated by each brand.
Count the number of products with a discount applied.
Filter stores by city, excluding a specific value.
Retrieve the orders placed in a specific month.
Get the staff details who do not have a manager assigned.
Find the products with a list price less than or equal to $100.
Sort the orders by required date in ascending order.
Retrieve the customers who have placed the most orders.
Calculate the average quantity of products in stock.
Get the order details for a specific store.
Count the number of orders with a completed status.
Filter products by their brand name, including a specific value.

--THESE ARE USED TO PERFORM FOLLOWING TASKS
SQL Functions:

AVG(): Used to calculate the average value.
COUNT(): Used to count the number of rows.
DISTINCT: Used to retrieve distinct values.
MAX(): Used to find the maximum value.
MIN(): Used to find the minimum value.
SUM(): Used to calculate the sum of values.
SQL Clauses:

SELECT: Used to retrieve data from one or more tables.
FROM: Specifies the table(s) to retrieve data from.
WHERE: Filters the rows based on a specific condition.
GROUP BY: Groups the rows based on one or more columns.
ORDER BY: Sorts the rows based on one or more columns.
JOIN: Combines rows from different tables based on a related column between them.
ON: Specifies the join condition in a JOIN operation.
DISTINCT: Removes duplicate rows from the result set.
ASC: Specifies ascending order in the ORDER BY clause.
DESC: Specifies descending order in the ORDER BY clause.